// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: api/movie.proto

package movie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowId        string                 `protobuf:"bytes,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	SeatId        string                 `protobuf:"bytes,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatRequest) Reset() {
	*x = GetSeatRequest{}
	mi := &file_api_movie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatRequest) ProtoMessage() {}

func (x *GetSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatRequest.ProtoReflect.Descriptor instead.
func (*GetSeatRequest) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{0}
}

func (x *GetSeatRequest) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *GetSeatRequest) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

type GetSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowId        string                 `protobuf:"bytes,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	SeatId        string                 `protobuf:"bytes,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatResponse) Reset() {
	*x = GetSeatResponse{}
	mi := &file_api_movie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatResponse) ProtoMessage() {}

func (x *GetSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatResponse.ProtoReflect.Descriptor instead.
func (*GetSeatResponse) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{1}
}

func (x *GetSeatResponse) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *GetSeatResponse) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *GetSeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BookSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowId        string                 `protobuf:"bytes,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	SeatId        string                 `protobuf:"bytes,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSeatRequest) Reset() {
	*x = BookSeatRequest{}
	mi := &file_api_movie_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSeatRequest) ProtoMessage() {}

func (x *BookSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSeatRequest.ProtoReflect.Descriptor instead.
func (*BookSeatRequest) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{2}
}

func (x *BookSeatRequest) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *BookSeatRequest) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *BookSeatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BookSeatRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type BookSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	ShowId        string                 `protobuf:"bytes,2,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	SeatId        string                 `protobuf:"bytes,3,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSeatResponse) Reset() {
	*x = BookSeatResponse{}
	mi := &file_api_movie_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSeatResponse) ProtoMessage() {}

func (x *BookSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSeatResponse.ProtoReflect.Descriptor instead.
func (*BookSeatResponse) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{3}
}

func (x *BookSeatResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookSeatResponse) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *BookSeatResponse) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *BookSeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BookSeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_movie_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{4}
}

func (x *PingRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_movie_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StartElectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartElectionRequest) Reset() {
	*x = StartElectionRequest{}
	mi := &file_api_movie_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartElectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartElectionRequest) ProtoMessage() {}

func (x *StartElectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartElectionRequest.ProtoReflect.Descriptor instead.
func (*StartElectionRequest) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{6}
}

func (x *StartElectionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type StartElectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartElectionResponse) Reset() {
	*x = StartElectionResponse{}
	mi := &file_api_movie_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartElectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartElectionResponse) ProtoMessage() {}

func (x *StartElectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartElectionResponse.ProtoReflect.Descriptor instead.
func (*StartElectionResponse) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{7}
}

func (x *StartElectionResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StartElectionResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *StartElectionResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ReplicateLogEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateLogEntryRequest) Reset() {
	*x = ReplicateLogEntryRequest{}
	mi := &file_api_movie_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateLogEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateLogEntryRequest) ProtoMessage() {}

func (x *ReplicateLogEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateLogEntryRequest.ProtoReflect.Descriptor instead.
func (*ReplicateLogEntryRequest) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{8}
}

func (x *ReplicateLogEntryRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ReplicateLogEntryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReplicateLogEntryRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ReplicateLogEntryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ReplicateLogEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateLogEntryResponse) Reset() {
	*x = ReplicateLogEntryResponse{}
	mi := &file_api_movie_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateLogEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateLogEntryResponse) ProtoMessage() {}

func (x *ReplicateLogEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateLogEntryResponse.ProtoReflect.Descriptor instead.
func (*ReplicateLogEntryResponse) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{9}
}

func (x *ReplicateLogEntryResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ReplicateLogEntryResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ReplicateLogEntryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReplicateLogEntryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RequestVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex  int32                  `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm   int32                  `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_api_movie_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{10}
}

func (x *RequestVoteRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *RequestVoteRequest) GetLastLogIndex() int32 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogTerm() int32 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_api_movie_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{11}
}

func (x *RequestVoteResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_movie_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{12}
}

func (x *LogEntry) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *LogEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LogEntry) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type AppendEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex  int32                  `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm   int32                  `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  int32                  `protobuf:"varint,6,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_api_movie_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{13}
}

func (x *AppendEntriesRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *AppendEntriesRequest) GetPrevLogIndex() int32 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogTerm() int32 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommit() int32 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type AppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_api_movie_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{14}
}

func (x *AppendEntriesResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_movie_proto protoreflect.FileDescriptor

const file_api_movie_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/movie.proto\x12\x05movie\"B\n" +
	"\x0eGetSeatRequest\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\tR\x06showId\x12\x17\n" +
	"\aseat_id\x18\x02 \x01(\tR\x06seatId\"[\n" +
	"\x0fGetSeatResponse\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\tR\x06showId\x12\x17\n" +
	"\aseat_id\x18\x02 \x01(\tR\x06seatId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"{\n" +
	"\x0fBookSeatRequest\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\tR\x06showId\x12\x17\n" +
	"\aseat_id\x18\x02 \x01(\tR\x06seatId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\x95\x01\n" +
	"\x10BookSeatResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x17\n" +
	"\ashow_id\x18\x02 \x01(\tR\x06showId\x12\x17\n" +
	"\aseat_id\x18\x03 \x01(\tR\x06seatId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"&\n" +
	"\vPingRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"?\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"/\n" +
	"\x14StartElectionRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"X\n" +
	"\x15StartElectionResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"{\n" +
	"\x18ReplicateLogEntryRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"w\n" +
	"\x19ReplicateLogEntryResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x95\x01\n" +
	"\x12RequestVoteRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\tR\vcandidateId\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x05R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x05R\vlastLogTerm\"L\n" +
	"\x13RequestVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\"\x7f\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\xe1\x01\n" +
	"\x14AppendEntriesRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12$\n" +
	"\x0eprev_log_index\x18\x03 \x01(\x05R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\x04 \x01(\x05R\vprevLogTerm\x12)\n" +
	"\aentries\x18\x05 \x03(\v2\x0f.movie.LogEntryR\aentries\x12#\n" +
	"\rleader_commit\x18\x06 \x01(\x05R\fleaderCommit\"E\n" +
	"\x15AppendEntriesResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\x8b\x01\n" +
	"\x12MovieTicketService\x128\n" +
	"\aGetSeat\x12\x15.movie.GetSeatRequest\x1a\x16.movie.GetSeatResponse\x12;\n" +
	"\bBookSeat\x12\x16.movie.BookSeatRequest\x1a\x17.movie.BookSeatResponse2\xe2\x01\n" +
	"\vNodeService\x12/\n" +
	"\x04Ping\x12\x12.movie.PingRequest\x1a\x13.movie.PingResponse\x12J\n" +
	"\rStartElection\x12\x1b.movie.StartElectionRequest\x1a\x1c.movie.StartElectionResponse\x12V\n" +
	"\x11ReplicateLogEntry\x12\x1f.movie.ReplicateLogEntryRequest\x1a .movie.ReplicateLogEntryResponse2\x9f\x01\n" +
	"\vRaftService\x12D\n" +
	"\vRequestVote\x12\x19.movie.RequestVoteRequest\x1a\x1a.movie.RequestVoteResponse\x12J\n" +
	"\rAppendEntries\x12\x1b.movie.AppendEntriesRequest\x1a\x1c.movie.AppendEntriesResponseB\x13Z\x11moviekv/api/movieb\x06proto3"

var (
	file_api_movie_proto_rawDescOnce sync.Once
	file_api_movie_proto_rawDescData []byte
)

func file_api_movie_proto_rawDescGZIP() []byte {
	file_api_movie_proto_rawDescOnce.Do(func() {
		file_api_movie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_movie_proto_rawDesc), len(file_api_movie_proto_rawDesc)))
	})
	return file_api_movie_proto_rawDescData
}

var file_api_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_movie_proto_goTypes = []any{
	(*GetSeatRequest)(nil),            // 0: movie.GetSeatRequest
	(*GetSeatResponse)(nil),           // 1: movie.GetSeatResponse
	(*BookSeatRequest)(nil),           // 2: movie.BookSeatRequest
	(*BookSeatResponse)(nil),          // 3: movie.BookSeatResponse
	(*PingRequest)(nil),               // 4: movie.PingRequest
	(*PingResponse)(nil),              // 5: movie.PingResponse
	(*StartElectionRequest)(nil),      // 6: movie.StartElectionRequest
	(*StartElectionResponse)(nil),     // 7: movie.StartElectionResponse
	(*ReplicateLogEntryRequest)(nil),  // 8: movie.ReplicateLogEntryRequest
	(*ReplicateLogEntryResponse)(nil), // 9: movie.ReplicateLogEntryResponse
	(*RequestVoteRequest)(nil),        // 10: movie.RequestVoteRequest
	(*RequestVoteResponse)(nil),       // 11: movie.RequestVoteResponse
	(*LogEntry)(nil),                  // 12: movie.LogEntry
	(*AppendEntriesRequest)(nil),      // 13: movie.AppendEntriesRequest
	(*AppendEntriesResponse)(nil),     // 14: movie.AppendEntriesResponse
}
var file_api_movie_proto_depIdxs = []int32{
	12, // 0: movie.AppendEntriesRequest.entries:type_name -> movie.LogEntry
	0,  // 1: movie.MovieTicketService.GetSeat:input_type -> movie.GetSeatRequest
	2,  // 2: movie.MovieTicketService.BookSeat:input_type -> movie.BookSeatRequest
	4,  // 3: movie.NodeService.Ping:input_type -> movie.PingRequest
	6,  // 4: movie.NodeService.StartElection:input_type -> movie.StartElectionRequest
	8,  // 5: movie.NodeService.ReplicateLogEntry:input_type -> movie.ReplicateLogEntryRequest
	10, // 6: movie.RaftService.RequestVote:input_type -> movie.RequestVoteRequest
	13, // 7: movie.RaftService.AppendEntries:input_type -> movie.AppendEntriesRequest
	1,  // 8: movie.MovieTicketService.GetSeat:output_type -> movie.GetSeatResponse
	3,  // 9: movie.MovieTicketService.BookSeat:output_type -> movie.BookSeatResponse
	5,  // 10: movie.NodeService.Ping:output_type -> movie.PingResponse
	7,  // 11: movie.NodeService.StartElection:output_type -> movie.StartElectionResponse
	9,  // 12: movie.NodeService.ReplicateLogEntry:output_type -> movie.ReplicateLogEntryResponse
	11, // 13: movie.RaftService.RequestVote:output_type -> movie.RequestVoteResponse
	14, // 14: movie.RaftService.AppendEntries:output_type -> movie.AppendEntriesResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_movie_proto_init() }
func file_api_movie_proto_init() {
	if File_api_movie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_movie_proto_rawDesc), len(file_api_movie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_movie_proto_goTypes,
		DependencyIndexes: file_api_movie_proto_depIdxs,
		MessageInfos:      file_api_movie_proto_msgTypes,
	}.Build()
	File_api_movie_proto = out.File
	file_api_movie_proto_goTypes = nil
	file_api_movie_proto_depIdxs = nil
}
