// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/movie.proto

package movie

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MovieTicketService_GetSeat_FullMethodName  = "/movie.MovieTicketService/GetSeat"
	MovieTicketService_BookSeat_FullMethodName = "/movie.MovieTicketService/BookSeat"
)

// MovieTicketServiceClient is the client API for MovieTicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieTicketServiceClient interface {
	GetSeat(ctx context.Context, in *GetSeatRequest, opts ...grpc.CallOption) (*GetSeatResponse, error)
	BookSeat(ctx context.Context, in *BookSeatRequest, opts ...grpc.CallOption) (*BookSeatResponse, error)
}

type movieTicketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieTicketServiceClient(cc grpc.ClientConnInterface) MovieTicketServiceClient {
	return &movieTicketServiceClient{cc}
}

func (c *movieTicketServiceClient) GetSeat(ctx context.Context, in *GetSeatRequest, opts ...grpc.CallOption) (*GetSeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeatResponse)
	err := c.cc.Invoke(ctx, MovieTicketService_GetSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieTicketServiceClient) BookSeat(ctx context.Context, in *BookSeatRequest, opts ...grpc.CallOption) (*BookSeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookSeatResponse)
	err := c.cc.Invoke(ctx, MovieTicketService_BookSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieTicketServiceServer is the server API for MovieTicketService service.
// All implementations must embed UnimplementedMovieTicketServiceServer
// for forward compatibility.
type MovieTicketServiceServer interface {
	GetSeat(context.Context, *GetSeatRequest) (*GetSeatResponse, error)
	BookSeat(context.Context, *BookSeatRequest) (*BookSeatResponse, error)
	mustEmbedUnimplementedMovieTicketServiceServer()
}

// UnimplementedMovieTicketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMovieTicketServiceServer struct{}

func (UnimplementedMovieTicketServiceServer) GetSeat(context.Context, *GetSeatRequest) (*GetSeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeat not implemented")
}
func (UnimplementedMovieTicketServiceServer) BookSeat(context.Context, *BookSeatRequest) (*BookSeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BookSeat not implemented")
}
func (UnimplementedMovieTicketServiceServer) mustEmbedUnimplementedMovieTicketServiceServer() {}
func (UnimplementedMovieTicketServiceServer) testEmbeddedByValue()                            {}

// UnsafeMovieTicketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieTicketServiceServer will
// result in compilation errors.
type UnsafeMovieTicketServiceServer interface {
	mustEmbedUnimplementedMovieTicketServiceServer()
}

func RegisterMovieTicketServiceServer(s grpc.ServiceRegistrar, srv MovieTicketServiceServer) {
	// If the following call panics, it indicates UnimplementedMovieTicketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MovieTicketService_ServiceDesc, srv)
}

func _MovieTicketService_GetSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieTicketServiceServer).GetSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieTicketService_GetSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieTicketServiceServer).GetSeat(ctx, req.(*GetSeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieTicketService_BookSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookSeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieTicketServiceServer).BookSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieTicketService_BookSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieTicketServiceServer).BookSeat(ctx, req.(*BookSeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MovieTicketService_ServiceDesc is the grpc.ServiceDesc for MovieTicketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieTicketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "movie.MovieTicketService",
	HandlerType: (*MovieTicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSeat",
			Handler:    _MovieTicketService_GetSeat_Handler,
		},
		{
			MethodName: "BookSeat",
			Handler:    _MovieTicketService_BookSeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/movie.proto",
}
