// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: api/movie.proto

package movie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowId        string                 `protobuf:"bytes,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	SeatId        string                 `protobuf:"bytes,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatRequest) Reset() {
	*x = GetSeatRequest{}
	mi := &file_api_movie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatRequest) ProtoMessage() {}

func (x *GetSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatRequest.ProtoReflect.Descriptor instead.
func (*GetSeatRequest) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{0}
}

func (x *GetSeatRequest) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *GetSeatRequest) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

type GetSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowId        string                 `protobuf:"bytes,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	SeatId        string                 `protobuf:"bytes,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatResponse) Reset() {
	*x = GetSeatResponse{}
	mi := &file_api_movie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatResponse) ProtoMessage() {}

func (x *GetSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatResponse.ProtoReflect.Descriptor instead.
func (*GetSeatResponse) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{1}
}

func (x *GetSeatResponse) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *GetSeatResponse) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *GetSeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BookSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowId        string                 `protobuf:"bytes,1,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	SeatId        string                 `protobuf:"bytes,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSeatRequest) Reset() {
	*x = BookSeatRequest{}
	mi := &file_api_movie_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSeatRequest) ProtoMessage() {}

func (x *BookSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSeatRequest.ProtoReflect.Descriptor instead.
func (*BookSeatRequest) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{2}
}

func (x *BookSeatRequest) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *BookSeatRequest) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *BookSeatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BookSeatRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type BookSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	ShowId        string                 `protobuf:"bytes,2,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	SeatId        string                 `protobuf:"bytes,3,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSeatResponse) Reset() {
	*x = BookSeatResponse{}
	mi := &file_api_movie_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSeatResponse) ProtoMessage() {}

func (x *BookSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_movie_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSeatResponse.ProtoReflect.Descriptor instead.
func (*BookSeatResponse) Descriptor() ([]byte, []int) {
	return file_api_movie_proto_rawDescGZIP(), []int{3}
}

func (x *BookSeatResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookSeatResponse) GetShowId() string {
	if x != nil {
		return x.ShowId
	}
	return ""
}

func (x *BookSeatResponse) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *BookSeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BookSeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_movie_proto protoreflect.FileDescriptor

const file_api_movie_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/movie.proto\x12\x05movie\"B\n" +
	"\x0eGetSeatRequest\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\tR\x06showId\x12\x17\n" +
	"\aseat_id\x18\x02 \x01(\tR\x06seatId\"[\n" +
	"\x0fGetSeatResponse\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\tR\x06showId\x12\x17\n" +
	"\aseat_id\x18\x02 \x01(\tR\x06seatId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"{\n" +
	"\x0fBookSeatRequest\x12\x17\n" +
	"\ashow_id\x18\x01 \x01(\tR\x06showId\x12\x17\n" +
	"\aseat_id\x18\x02 \x01(\tR\x06seatId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\x95\x01\n" +
	"\x10BookSeatResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x17\n" +
	"\ashow_id\x18\x02 \x01(\tR\x06showId\x12\x17\n" +
	"\aseat_id\x18\x03 \x01(\tR\x06seatId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage2\x8b\x01\n" +
	"\x12MovieTicketService\x128\n" +
	"\aGetSeat\x12\x15.movie.GetSeatRequest\x1a\x16.movie.GetSeatResponse\x12;\n" +
	"\bBookSeat\x12\x16.movie.BookSeatRequest\x1a\x17.movie.BookSeatResponseB\x13Z\x11moviekv/api/movieb\x06proto3"

var (
	file_api_movie_proto_rawDescOnce sync.Once
	file_api_movie_proto_rawDescData []byte
)

func file_api_movie_proto_rawDescGZIP() []byte {
	file_api_movie_proto_rawDescOnce.Do(func() {
		file_api_movie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_movie_proto_rawDesc), len(file_api_movie_proto_rawDesc)))
	})
	return file_api_movie_proto_rawDescData
}

var file_api_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_movie_proto_goTypes = []any{
	(*GetSeatRequest)(nil),   // 0: movie.GetSeatRequest
	(*GetSeatResponse)(nil),  // 1: movie.GetSeatResponse
	(*BookSeatRequest)(nil),  // 2: movie.BookSeatRequest
	(*BookSeatResponse)(nil), // 3: movie.BookSeatResponse
}
var file_api_movie_proto_depIdxs = []int32{
	0, // 0: movie.MovieTicketService.GetSeat:input_type -> movie.GetSeatRequest
	2, // 1: movie.MovieTicketService.BookSeat:input_type -> movie.BookSeatRequest
	1, // 2: movie.MovieTicketService.GetSeat:output_type -> movie.GetSeatResponse
	3, // 3: movie.MovieTicketService.BookSeat:output_type -> movie.BookSeatResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_movie_proto_init() }
func file_api_movie_proto_init() {
	if File_api_movie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_movie_proto_rawDesc), len(file_api_movie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_movie_proto_goTypes,
		DependencyIndexes: file_api_movie_proto_depIdxs,
		MessageInfos:      file_api_movie_proto_msgTypes,
	}.Build()
	File_api_movie_proto = out.File
	file_api_movie_proto_goTypes = nil
	file_api_movie_proto_depIdxs = nil
}
